version: '3.8'

services:
  web:
    build: .
    command: sh -c './wait-for-db.sh && pytest'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: catdatabase
      POSTGRES_USER: bynet
      POSTGRES_PASSWORD: 1q2w3e4r+
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: catdatabase
      POSTGRES_USER: bynet
      POSTGRES_PASSWORD: 1q2w3e4r+
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
